//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string HouseName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public int Floor { get; set; }
        public int Bedroom { get; set; }
        public bool Kitchen { get; set; }
        public bool Dining { get; set; }
        public string Family { get; set; }
        public string Bachelor { get; set; }
        public string Office { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int Rent { get; set; }
        public string Additional { get; set; }
        public byte[] Image { get; set; }
        public int isDeleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
